In [20]:
from datetime import date
a=date(2000, 1, 2)
my_dict = {a:1}
my_dict.keys()

dict_keys([datetime.date(2000, 1, 2)])

In [24]:
(lambda x, y: x + y)(1, 2)

3

In [25]:
from pandas import DataFrame

In [26]:
data_frame = DataFrame.from_dict({
    "name": ["Kirill", "Ivan", "Anton"], 
    "age": [31, 26, 40]
})

In [27]:
data_frame

     name  age
0  Kirill   31
1    Ivan   26
2   Anton   40

In [28]:
data_frame.set_index("name")

        age
name
Kirill   31
Ivan     26
Anton    40

In [67]:
from pandas import DataFrame

my_data = DataFrame.from_dict({
    "name": ["Kirill", "Ivan", "Anton"], 
    "age":  [31, 26, 40]
})

my_data.index=[1, 2]

#my_data.set_index("name")

ValueError: Length mismatch: Expected axis has 3 elements, new values have 2 elements

In [65]:
my_data.loc[1].at("age")

TypeError: '_AtIndexer' object is not callable

In [57]:
df = DataFrame.from_dict({"x": [1, 2, 3], "y": [1, 4, 9]})

In [58]:
df.set_index("y", inplace=True)

In [60]:
df.at(1, 9)

TypeError: '_AtIndexer' object is not callable